[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.5.1"

# Production environment (main branch)
[context.production]
  environment = { PUBLIC_ENVIRONMENT = "production" }

[context.production.environment]
  NODE_ENV = "production"

# Staging environment (staging branch)  
[context.staging]
  environment = { PUBLIC_ENVIRONMENT = "staging" }

[context.staging.environment]
  NODE_ENV = "production"

# Development environment (dev branch)
[context.dev]
  environment = { PUBLIC_ENVIRONMENT = "development" }

[context.dev.environment]
  NODE_ENV = "development"

# Branch deploy environment
[context.branch-deploy.environment]
  NODE_ENV = "development"
  PUBLIC_ENVIRONMENT = "preview"

# Deploy preview environment (PRs)
[context.deploy-preview.environment]
  NODE_ENV = "development"
  PUBLIC_ENVIRONMENT = "preview"

# SPA rewrite: serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
  # Content Security Policy - adjust as needed for your dependencies
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https://plausible.io https://cdn.jsdelivr.net;
    style-src 'self' 'unsafe-inline';
    img-src 'self' data: https: blob:;
    font-src 'self' data:;
    connect-src 'self' https://plausible.io;
    frame-ancestors 'none';
    base-uri 'self';
    form-action 'self';
    upgrade-insecure-requests;
  """
  
  # Security headers
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-XSS-Protection = "1; mode=block"
  
  # Permission policy (formerly Feature Policy)
  Permissions-Policy = """
    accelerometer=(),
    camera=(),
    geolocation=(),
    gyroscope=(),
    magnetometer=(),
    microphone=(),
    payment=(),
    usb=()
  """
  
  # HSTS (uncomment when using HTTPS in production)
  # Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache static assets
[[headers]]
  for = "/fonts/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
  Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.js"
  [headers.values]
  Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=604800"