name: CI

on:
  pull_request:
    branches: [ test, main ]
  push:
    branches: [ test, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.5.1
      - run: npm ci
      - run: npm run lint
      - run: npm test --if-present
      - run: npm run build